---
domain_name: rstudio-test.dev.rc.nectar.org.au
rstudio_master_ip: '{{ hostvars[groups["rstudio-test-master"][0]].ansible_default_ipv4.address }}'
rstudio_server_load_balancer_cookie: df4474f6-33e6-4528-ba0d-d19554edc671
rstudio_server_load_balancer_nodes: "{{ groups['rstudio-test'] | map('extract', hostvars, ['ansible_ssh_host']) | list }}"

# vim: syntax=yaml
