---
- name: Install apache2 and shibboleth module
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
    - apache2
    - libapache2-mod-shib2

- name: Enable apache2 shibboleth module
  command: a2enmod shib2
  notify:
    - restart apache

- name: Enable apache2 ssl module
  command: a2enmod ssl
  notify:
    - restart apache
