---
- name: install pkgs
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ nss_pam_ldap_dep_pkgs }}'

- name: remove nscd
  package:
    name: nscd
    state: absent
  notify: restart nslcd

- name: templatize
  become: yes
  with_items:
    - file: etc/nslcd.conf
      mode: '0600'
    - file: etc/nsswitch.conf
      mode: '0644'
    - file: etc/pam.d/ldap
      mode: '0600'
  template: >-
    src={{ item.file }}.j2
    dest=/{{ item.file }}
    mode={{ item.mode }}
  notify: restart nslcd

- name: configure pam common-session
  become: yes
  lineinfile: 
    dest: /etc/pam.d/common-session
    state: present
    regexp: '^session\s+required\s+pam_mkhomedir.so'
    line: 'session required pam_mkhomedir.so umask=0022'
