---

- name: Manage OpenLDAP service
  hosts: [ 'debops_service_slapd', 'debops_slapd' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ slapd_ferm_dependent_rules }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers_dependent_allow:
        - '{{ slapd_tcpwrappers_dependent_allow }}'

    - role: debops.slapd
      tags: [ 'role::slapd' ]

