---

- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:

    - include_vars: defaults/main.yml

    - include_vars: test_vars.yml

    - include: tasks/main.yml

    - name: restart httpd
      sudo: yes
      when: ansible_os_family == 'Debian'
      service: name=apache2
               state=restarted

    - name: restart httpd
      sudo: yes
      when: ansible_os_family == 'RedHat'
      service: name=httpd
               state=restarted

    - name: Check to see if apache is running
      uri:
        url: http://127.0.0.1:80/
        method: GET
        status_code: 200

    - name: Check to see if apache shib2 module is loaded
      uri:
        url: https://127.0.0.1:443/Shibboleth.sso/Status
        method: GET
        status_code: 200
        validate_certs: no

  handlers:
    - include: handlers/main.yml
