---

- name: Configure LDAP connection security
  ldap_attr:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    name: 'olcSecurity'
    values: '{{ slapd_ldap_security }}'
    state: 'present'

- name: Configure LDAP indices
  ldap_attr:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    name: 'olcDbIndex'
    values: '{{ slapd_ldap_index }}'
    state: 'exact'

#- name: Configure LDAP Access Control List
#  ldap_attr:
#    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
#    name: 'olcAccess'
#    values: '{{ lookup("template", "lookup/slapd_ldap_access_control_list.j2") | from_yaml }}'
#    state: 'exact'

- name: Add Groups entry
  ldap_entry:
    dn: '{{slapd_ldapscripts_gsuffix}},{{ slapd_ldapscripts_suffix }}'
    objectClass: organizationalUnit
    bind_dn: '{{ slapd_basedn_admin }}'
    bind_pw: '{{ lookup("password", slapd_ldapscripts_password_lookup) }}'

- name: Add Users entry
  ldap_entry:
    dn: '{{slapd_ldapscripts_usuffix}},{{ slapd_ldapscripts_suffix }}'
    objectClass: organizationalUnit
    bind_dn: '{{ slapd_basedn_admin }}'
    bind_pw: '{{ lookup("password", slapd_ldapscripts_password_lookup) }}'
